sudo: required
services:
  - docker

before_install:
  - docker build -t luketowell/frontend-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true luketowell/frontend-docker npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "Encrypted <access-key-id>=AKIAIUMA6RM7KVXOOZSA"
  secret_access_key:
    secure: "Encypted <secret-access-key>=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"
  region: "eu-west-2"  
  app: "frontend-docker"
  env: "FrontendDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-182946098473"
  on:
    branch: master